// --- AI Model File Path (DO NOT DELETE) ---
// FilePath: stackblitz > angular > basic-filter-reducer-example > src > main.ts
// Updated: 2026-04-22 08:54
//	 Generated by pathcomment [tab] (see .vscode/typescript.code-snippets) or
//	 cmd+alt+j (see .vscode/keybindings.json)
// --- END AI MODEL FILE PATH ---

/**
 * Application bootstrap entry point.
 *
 * Bootstraps the root ExampleComponent as a standalone Angular application
 * using the provider configuration defined in appConfig.
 */
import { bootstrapApplication } from '@angular/platform-browser';
import { appConfig } from './app/app.config';
import { ExampleComponent } from './app/example.component';

// eslint-disable-next-line
bootstrapApplication(ExampleComponent, appConfig).catch((err: any) =>
  console.error(err)
);
